x = input('Digite algo: ')
print(type(x))
print('É um número? {}'.format(x.isnumeric()))
print('É uma alfa númerico? {}'.format(x.isalnum()))
print('É alfabético? {}'.format(x.isalpha()))
print('É digitado? {}'.format(x.isdigit()))
print('É decimal? {}'.format(x.isdecimal()))
print('É um identificador? {}'.format(x.isidentifier()))
print('É somente minusculas? {}'.format(x.islower()))
print('É imprimivel? {}'.format(x.isprintable()))
print('É somente espaços? {}'.format(x.isspace()))
print('Está capitalizado? {}'.format(x.istitle()))
print('Está em maiusculo? {}'.format(x.isupper()))


